
package directionClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DirectionServiceService", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", wsdlLocation = "http://localhost:8888/hello?wsdl")
public class DirectionServiceService
    extends Service
{

    private final static URL DIRECTIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DIRECTIONSERVICESERVICE_EXCEPTION;
    private final static QName DIRECTIONSERVICESERVICE_QNAME = new QName("http://webservice.gestionetudiant.ensup.eu/", "DirectionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIRECTIONSERVICESERVICE_WSDL_LOCATION = url;
        DIRECTIONSERVICESERVICE_EXCEPTION = e;
    }

    public DirectionServiceService() {
        super(__getWsdlLocation(), DIRECTIONSERVICESERVICE_QNAME);
    }

    public DirectionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIRECTIONSERVICESERVICE_QNAME, features);
    }

    public DirectionServiceService(URL wsdlLocation) {
        super(wsdlLocation, DIRECTIONSERVICESERVICE_QNAME);
    }

    public DirectionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIRECTIONSERVICESERVICE_QNAME, features);
    }

    public DirectionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDirectionService
     */
    @WebEndpoint(name = "DirectionServicePort")
    public IDirectionService getDirectionServicePort() {
        return super.getPort(new QName("http://webservice.gestionetudiant.ensup.eu/", "DirectionServicePort"), IDirectionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDirectionService
     */
    @WebEndpoint(name = "DirectionServicePort")
    public IDirectionService getDirectionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.gestionetudiant.ensup.eu/", "DirectionServicePort"), IDirectionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIRECTIONSERVICESERVICE_EXCEPTION!= null) {
            throw DIRECTIONSERVICESERVICE_EXCEPTION;
        }
        return DIRECTIONSERVICESERVICE_WSDL_LOCATION;
    }

}
