
package directionClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDirectionService", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDirectionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierEtudiant", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.ModifierEtudiant")
    @ResponseWrapper(localName = "modifierEtudiantResponse", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.ModifierEtudiantResponse")
    @Action(input = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/modifierEtudiantRequest", output = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/modifierEtudiantResponse")
    public int modifierEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0);

    /**
     * 
     * @return
     *     returns java.util.List<directionClient.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listerEtudiants", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.ListerEtudiants")
    @ResponseWrapper(localName = "listerEtudiantsResponse", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.ListerEtudiantsResponse")
    @Action(input = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/listerEtudiantsRequest", output = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/listerEtudiantsResponse")
    public List<Etudiant> listerEtudiants();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creerEtudiant", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.CreerEtudiant")
    @ResponseWrapper(localName = "creerEtudiantResponse", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.CreerEtudiantResponse")
    @Action(input = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/creerEtudiantRequest", output = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/creerEtudiantResponse")
    public int creerEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns directionClient.Etudiant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lireInfoEtudiant", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.LireInfoEtudiant")
    @ResponseWrapper(localName = "lireInfoEtudiantResponse", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.LireInfoEtudiantResponse")
    @Action(input = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/lireInfoEtudiantRequest", output = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/lireInfoEtudiantResponse")
    public Etudiant lireInfoEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerEtudiant", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.SupprimerEtudiant")
    @ResponseWrapper(localName = "supprimerEtudiantResponse", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.SupprimerEtudiantResponse")
    @Action(input = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/supprimerEtudiantRequest", output = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/supprimerEtudiantResponse")
    public int supprimerEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterEtudiantCours", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.AjouterEtudiantCours")
    @ResponseWrapper(localName = "ajouterEtudiantCoursResponse", targetNamespace = "http://webservice.gestionetudiant.ensup.eu/", className = "directionClient.AjouterEtudiantCoursResponse")
    @Action(input = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/ajouterEtudiantCoursRequest", output = "http://webservice.gestionetudiant.ensup.eu/IDirectionService/ajouterEtudiantCoursResponse")
    public int ajouterEtudiantCours(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Cours arg1);

}
